[package]
name = "fondant-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
fondant = { git = "https://github.com/Cachorr0/fondant" }
